---
apiVersion: v1
kind: ConfigMap
metadata:
  name: hazelcast-cm
data:
  hazelcast.yaml: |
    hazelcast:
      network:
        join:
          multicast:
            enabled: false
          kubernetes:
            enabled: true
        rest-api:
          enabled: true
