apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: hazelcast-cluster-role
rules:
  - apiGroups:
      - ""
    resources:
      - endpoints
      - pods
      - nodes
      - services
    verbs:
      - get
      - list

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: hazelcast-cluster-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: hazelcast-cluster-role
subjects:
  - kind: ServiceAccount
    name: hazelcast-sa
    namespace: default

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: hazelcast-sa
  namespace: default

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hazelcast
  labels:
    app: hazelcast
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hazelcast
  template:
    metadata:
      labels:
        app: hazelcast
    spec:
      serviceAccountName: hazelcast-sa
      containers:
        - name: hazelcast
          image: hazelcast/hazelcast:4.1.2
          ports:
            - containerPort: 5701
          env:
            - name: JAVA_OPTS
              value: "-Dhazelcast.config=/data/hazelcast/hazelcast.yaml"
            - name: LOGGING_LEVEL
              value: INFO
          volumeMounts:
            - name: hazelcast-cm
              mountPath: /data/hazelcast
      volumes:
        - name: hazelcast-cm
          configMap:
            name: hazelcast-cm
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: hazelcast-cm
data:
  hazelcast.yaml: |
    hazelcast:
      network:
        join:
          multicast:
            enabled: false
          kubernetes:
            enabled: true
        rest-api:
          enabled: true
