---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hazelcast
  labels:
    app: hazelcast
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hazelcast
  template:
    metadata:
      labels:
        app: hazelcast
    spec:
      serviceAccountName: hazelcast-sa
      containers:
        - name: hazelcast
          image: hazelcast/hazelcast:4.1.2
          ports:
            - containerPort: 5701
          env:
            - name: JAVA_OPTS
              value: "-Dhazelcast.config=/data/hazelcast/hazelcast.yaml"
            - name: LOGGING_LEVEL
              value: INFO
              #value: DEBUG
              #value: TRACE
          volumeMounts:
            - name: hazelcast-cm
              mountPath: /data/hazelcast
      volumes:
        - name: hazelcast-cm
          configMap:
            name: hazelcast-cm
